// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Movierok {
    
    
    public partial class Configuration {
        
        private Gtk.VBox boxConfig;
        
        private Gtk.Frame frmGeneral;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.Table table4;
        
        private Gtk.FileChooserButton chsrPlayer;
        
        private Gtk.Label lblPlayer;
        
        private Gtk.Label lblUsername;
        
        private Gtk.Entry txtUsername;
        
        private Gtk.Label GtkLabel1;
        
        private Gtk.Frame frmAdvanced;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.Table table5;
        
        private Gtk.ComboBox cmbProfiles;
        
        private Gtk.Label lblProfiles;
        
        private Gtk.Label lblAdvanced;
        
        private Gtk.VBox vbox1;
        
        private Gtk.Label lblAccount;
        
        private Gtk.Button btnAccount;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Movierok.Configuration
            Stetic.BinContainer.Attach(this);
            this.Name = "Movierok.Configuration";
            // Container child Movierok.Configuration.Gtk.Container+ContainerChild
            this.boxConfig = new Gtk.VBox();
            this.boxConfig.Name = "boxConfig";
            this.boxConfig.Spacing = 6;
            // Container child boxConfig.Gtk.Box+BoxChild
            this.frmGeneral = new Gtk.Frame();
            this.frmGeneral.Name = "frmGeneral";
            this.frmGeneral.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frmGeneral.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.table4 = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.table4.Name = "table4";
            this.table4.RowSpacing = ((uint)(6));
            this.table4.ColumnSpacing = ((uint)(6));
            // Container child table4.Gtk.Table+TableChild
            this.chsrPlayer = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
            this.chsrPlayer.Name = "chsrPlayer";
            this.table4.Add(this.chsrPlayer);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table4[this.chsrPlayer]));
            w1.TopAttach = ((uint)(1));
            w1.BottomAttach = ((uint)(2));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.lblPlayer = new Gtk.Label();
            this.lblPlayer.Name = "lblPlayer";
            this.lblPlayer.Xalign = 0F;
            this.lblPlayer.LabelProp = Mono.Unix.Catalog.GetString("Player:");
            this.table4.Add(this.lblPlayer);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table4[this.lblPlayer]));
            w2.TopAttach = ((uint)(1));
            w2.BottomAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.lblUsername = new Gtk.Label();
            this.lblUsername.Name = "lblUsername";
            this.lblUsername.Xalign = 0F;
            this.lblUsername.LabelProp = Mono.Unix.Catalog.GetString("Username:");
            this.table4.Add(this.lblUsername);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table4[this.lblUsername]));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.txtUsername = new Gtk.Entry();
            this.txtUsername.CanFocus = true;
            this.txtUsername.Name = "txtUsername";
            this.txtUsername.IsEditable = true;
            this.txtUsername.InvisibleChar = '●';
            this.table4.Add(this.txtUsername);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table4[this.txtUsername]));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment.Add(this.table4);
            this.frmGeneral.Add(this.GtkAlignment);
            this.GtkLabel1 = new Gtk.Label();
            this.GtkLabel1.Name = "GtkLabel1";
            this.GtkLabel1.LabelProp = Mono.Unix.Catalog.GetString("<b>General</b>");
            this.GtkLabel1.UseMarkup = true;
            this.frmGeneral.LabelWidget = this.GtkLabel1;
            this.boxConfig.Add(this.frmGeneral);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.boxConfig[this.frmGeneral]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child boxConfig.Gtk.Box+BoxChild
            this.frmAdvanced = new Gtk.Frame();
            this.frmAdvanced.Name = "frmAdvanced";
            this.frmAdvanced.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frmAdvanced.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.table5 = new Gtk.Table(((uint)(1)), ((uint)(2)), false);
            this.table5.Name = "table5";
            this.table5.RowSpacing = ((uint)(6));
            this.table5.ColumnSpacing = ((uint)(6));
            // Container child table5.Gtk.Table+TableChild
            this.cmbProfiles = Gtk.ComboBox.NewText();
            this.cmbProfiles.Name = "cmbProfiles";
            this.cmbProfiles.Active = 0;
            this.table5.Add(this.cmbProfiles);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table5[this.cmbProfiles]));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.lblProfiles = new Gtk.Label();
            this.lblProfiles.Name = "lblProfiles";
            this.lblProfiles.Xalign = 0F;
            this.lblProfiles.LabelProp = Mono.Unix.Catalog.GetString("Firefox Profile:");
            this.table5.Add(this.lblProfiles);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table5[this.lblProfiles]));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment1.Add(this.table5);
            this.frmAdvanced.Add(this.GtkAlignment1);
            this.lblAdvanced = new Gtk.Label();
            this.lblAdvanced.Name = "lblAdvanced";
            this.lblAdvanced.LabelProp = Mono.Unix.Catalog.GetString("<b>Advanced</b>");
            this.lblAdvanced.UseMarkup = true;
            this.frmAdvanced.LabelWidget = this.lblAdvanced;
            this.boxConfig.Add(this.frmAdvanced);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.boxConfig[this.frmAdvanced]));
            w12.Position = 1;
            w12.Expand = false;
            w12.Fill = false;
            // Container child boxConfig.Gtk.Box+BoxChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.lblAccount = new Gtk.Label();
            this.lblAccount.Name = "lblAccount";
            this.lblAccount.LabelProp = Mono.Unix.Catalog.GetString("Don't have an account?");
            this.vbox1.Add(this.lblAccount);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox1[this.lblAccount]));
            w13.Position = 0;
            w13.Expand = false;
            w13.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.btnAccount = new Gtk.Button();
            this.btnAccount.CanFocus = true;
            this.btnAccount.Name = "btnAccount";
            this.btnAccount.UseUnderline = true;
            this.btnAccount.Label = "Sign up for movierok";
            this.vbox1.Add(this.btnAccount);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox1[this.btnAccount]));
            w14.Position = 1;
            w14.Expand = false;
            w14.Fill = false;
            this.boxConfig.Add(this.vbox1);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.boxConfig[this.vbox1]));
            w15.PackType = ((Gtk.PackType)(1));
            w15.Position = 2;
            w15.Expand = false;
            w15.Fill = false;
            this.Add(this.boxConfig);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.cmbProfiles.Changed += new System.EventHandler(this.OnCmbProfilesChanged);
            this.btnAccount.Clicked += new System.EventHandler(this.OnBtnAccountClicked);
        }
    }
}
