// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Movierok {
    
    
    public partial class Configuration {
        
        private Gtk.Frame FrmGeneral;
        
        private Gtk.VBox vbox4;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Label LblUsername;
        
        private Gtk.Entry TxtUsername;
        
        private Gtk.HBox hbox5;
        
        private Gtk.Label LblPlayer;
        
        private Gtk.Entry TxtPlayer;
        
        private Gtk.Label GtkLabel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Movierok.Configuration
            Stetic.BinContainer.Attach(this);
            this.Name = "Movierok.Configuration";
            // Container child Movierok.Configuration.Gtk.Container+ContainerChild
            this.FrmGeneral = new Gtk.Frame();
            this.FrmGeneral.Name = "FrmGeneral";
            this.FrmGeneral.ShadowType = ((Gtk.ShadowType)(0));
            // Container child FrmGeneral.Gtk.Container+ContainerChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.LblUsername = new Gtk.Label();
            this.LblUsername.Name = "LblUsername";
            this.LblUsername.LabelProp = Mono.Unix.Catalog.GetString("Username: ");
            this.hbox4.Add(this.LblUsername);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox4[this.LblUsername]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.TxtUsername = new Gtk.Entry();
            this.TxtUsername.CanFocus = true;
            this.TxtUsername.Name = "TxtUsername";
            this.TxtUsername.IsEditable = true;
            this.TxtUsername.InvisibleChar = '●';
            this.hbox4.Add(this.TxtUsername);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox4[this.TxtUsername]));
            w2.Position = 1;
            this.vbox4.Add(this.hbox4);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox4]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox5 = new Gtk.HBox();
            this.hbox5.Name = "hbox5";
            this.hbox5.Spacing = 6;
            // Container child hbox5.Gtk.Box+BoxChild
            this.LblPlayer = new Gtk.Label();
            this.LblPlayer.Name = "LblPlayer";
            this.LblPlayer.LabelProp = Mono.Unix.Catalog.GetString("Player:        ");
            this.hbox5.Add(this.LblPlayer);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox5[this.LblPlayer]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.TxtPlayer = new Gtk.Entry();
            this.TxtPlayer.CanFocus = true;
            this.TxtPlayer.Name = "TxtPlayer";
            this.TxtPlayer.IsEditable = true;
            this.TxtPlayer.InvisibleChar = '●';
            this.hbox5.Add(this.TxtPlayer);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox5[this.TxtPlayer]));
            w5.Position = 1;
            this.vbox4.Add(this.hbox5);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox5]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            this.FrmGeneral.Add(this.vbox4);
            this.GtkLabel = new Gtk.Label();
            this.GtkLabel.Name = "GtkLabel";
            this.GtkLabel.LabelProp = Mono.Unix.Catalog.GetString("<b>General</b>");
            this.GtkLabel.UseMarkup = true;
            this.FrmGeneral.LabelWidget = this.GtkLabel;
            this.Add(this.FrmGeneral);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.TxtUsername.Changed += new System.EventHandler(this.OnTxtUsernameChanged);
            this.TxtPlayer.Changed += new System.EventHandler(this.OnTxtPlayerChanged);
        }
    }
}
